### ISSUE TITLE
Integration with Cucumber?

### ISSUE THREAD

**Issue by SimonBo** [thoughtbot/formulaic#43]
I tried using formulaic in my Cucumber steps:
fill_form(:resume, FactoryGirl.attributes_for(:resume))

Getting 
undefined method `fill_form' for #<Cucumber::Rails::World:0x007f8351584630> (NoMethodError)

Is Cucumber supported at all? If not, will it be supported?

**Comment by calebthompson** [comment]
You probably need to include `Formulaic::Dsl` in `World`.
