### ISSUE TITLE
Formulaic does not know how to fill in a Symbol value

### ISSUE THREAD

**Issue by KevinSjoberg** [thoughtbot/formulaic#50]
Hi,

I'm using Formulaic in a project of mine and we use an `enum` type for selecting a user's role. Since enum values are of type `Symbol`, Formulaic complains with the following error message:

> Formulaic does not know how to fill in a Symbol value

My suggestion would be to convert symbol values to strings by calling `#to_s` on them and then let `StringInput` class handle it as usual. What do you think about this? Can this have any side effects that I'm not seeing right now?

I'd love to send a pull request as we decide on a solution! :smile: 

Cheers,
Kevin

**Comment by calebthompson** [comment]
It makes sense to me to treat them the same as Strings, which would try to select and fill_in at least.

**Comment by KevinSjoberg** [comment]
@calebthompson I've sent a pull request addressing this issue. You can find at #51.

**Comment by KevinSjoberg** [comment]
Closed by #51.

**Comment by KevinSjoberg** [comment]
@calebthompson I'm closing this since we've merged #51.
