### ISSUE TITLE
Capybara deprecation errors

### ISSUE THREAD

**Issue by mjankowski** [thoughtbot/formulaic#73]
Starting with a recent capybara release, using formulaic kicks out deprecation warnings. Example from the formulaic feature spec:

```
Locator #<Formulaic::Label:0x007fc83c29c4b0 @model_name=:user, @attribute=:name, @action=:new> must be an instance of String or Symbol. This will raise an error in a future version of Capybara.
```

**Comment by calebthompson** [comment]
Ok I’ll look into it. Hopefully we can make a small change like calling to_s on ourselves.

**Comment by calebthompson** [comment]
https://github.com/thoughtbot/formulaic/pull/74
